pub struct TaintSource {
    pub kind: &'static str,
    pub patterns: &'static [&'static str],
    pub extensions: Option<&'static [&'static str]>,
}

pub static TAINT_SOURCES: &[TaintSource] = &[
    // HTTP parameters
    TaintSource {
        kind: "HttpParam",
        patterns: &[
            "request.get[",
            "request.get.get(",
            "request.post[",
            "request.post.get(",
            "request.args.get(",
            "request.args[",
            "request.form[",
            "request.form.get(",
            "req.query.",
            "req.query[",
            "req.params.",
            "req.params[",
            "request.getparameter(",
            "request.getparametervalues(",
            "@requestparam",
            "@pathvariable",
            "@queryparam",
            "request.query[",
            "request.form[",
            "c.param(",
            "c.query(",
            "c.defaultquery(",
            "r.url.query()",
            "r.formvalue(",
        ],
        extensions: None,
    },
    // HTTP body
    TaintSource {
        kind: "HttpBody",
        patterns: &[
            "request.body",
            "req.body",
            "request.json",
            "request.data",
            "request.get_json(",
            "request.content",
            "@requestbody",
            "request.getinputstream(",
            "request.body",
            "readfromjsonasync(",
            "c.bindjson(",
            "c.shouldbindjson(",
            "json.newdecoder(r.body)",
        ],
        extensions: None,
    },
    // HTTP headers
    TaintSource {
        kind: "HttpHeader",
        patterns: &[
            "request.headers[",
            "request.headers.get(",
            "req.headers[",
            "req.headers.get(",
            "req.header(",
            "request.getheader(",
            "request.meta[",
            "request.headers[",
            "r.header.get(",
        ],
        extensions: None,
    },
    // File reads
    TaintSource {
        kind: "FileRead",
        patterns: &[
            "open(",
            "readfile(",
            "fs.read",
            "file(",
            "fs.readfilesync(",
            "fs.readfile(",
            "files.readallbytes(",
            "files.readstring(",
            "file.readalltext(",
            "file.readalllines(",
            "os.readfile(",
            "ioutil.readfile(",
        ],
        extensions: None,
    },
    // User input (CLI/console)
    TaintSource {
        kind: "UserInput",
        patterns: &[
            "input(",
            "readline(",
            "scanner(",
            "process.stdin",
            "sys.stdin",
            "console.readline(",
            "bufio.newreader(os.stdin)",
            "std::io::stdin()",
        ],
        extensions: None,
    },
    // Environment variables (can be attacker-controlled in some contexts)
    TaintSource {
        kind: "EnvVar",
        patterns: &[
            "os.environ[",
            "os.environ.get(",
            "os.getenv(",
            "process.env.",
            "process.env[",
            "system.getenv(",
            "environment.getenvironmentvariable(",
            "os.getenv(",
            "std::env::var(",
        ],
        extensions: None,
    },
];
