use std::collections::HashMap;
use std::io::IsTerminal;
use std::path::Path;

use anyhow::Result;
use infigraph_core::Infigraph;
use infigraph_languages::bundled_registry;

pub(crate) fn cmd_init(root: &Path, group: Option<&str>, quick: bool, yes: bool) -> Result<()> {
    let registry = bundled_registry()?;
    let mut prism = Infigraph::open(root, registry)?;
    prism.init()?;
    println!("Initialized infigraph in {}", root.display());
    println!("Graph database created at .infigraph/graph/");

    // --- Wizard steps (skipped with --quick) ---
    if !quick {
        // Step 1: Detect languages
        let languages = detect_languages(root);
        if !languages.is_empty() {
            let lang_parts: Vec<String> = languages
                .iter()
                .map(|(name, count)| format!("{name} ({count} files)"))
                .collect();
            println!("\nDetected languages: {}", lang_parts.join(", "));
        } else {
            println!("\nNo source files detected.");
        }

        // Step 2: Suggest .infigraphignore
        let suggestions = suggest_ignore_entries(root, &languages);
        if !suggestions.is_empty() {
            println!("\nSuggested .infigraphignore entries:");
            for entry in &suggestions {
                println!("  {entry}");
            }

            let ignore_path = root.join(".infigraphignore");
            if !ignore_path.exists() {
                let should_write = if yes {
                    true
                } else if std::io::stdin().is_terminal() {
                    print!("\nWrite .infigraphignore with these entries? [Y/n] ");
                    use std::io::Write;
                    std::io::stdout().flush()?;
                    let answer = read_line_stdin();
                    answer.is_empty() || answer.starts_with('y') || answer.starts_with('Y')
                } else {
                    // Non-TTY: auto-write
                    true
                };

                if should_write {
                    let content = format!(
                        "# Auto-generated by infigraph init\n{}\n",
                        suggestions.join("\n")
                    );
                    std::fs::write(&ignore_path, content)?;
                    println!("  Wrote .infigraphignore");
                }
            } else {
                println!("  .infigraphignore already exists, skipping.");
            }
        }

        // Step 3: Optionally run first index
        let should_index = if yes {
            true
        } else if std::io::stdin().is_terminal() {
            print!("\nRun initial index? [Y/n] ");
            use std::io::Write;
            std::io::stdout().flush()?;
            let answer = read_line_stdin();
            answer.is_empty() || answer.starts_with('y') || answer.starts_with('Y')
        } else {
            // Non-TTY: skip index
            false
        };

        if should_index {
            println!();
            crate::index::cmd_index(root, false, false)?;
        }
    }

    // --- Existing logic: agent instructions ---
    let group_context = if let Some(group_name) = group {
        use infigraph_core::multi::Registry;
        let reg = Registry::load().unwrap_or_default();
        if let Some(g) = reg.groups.get(group_name) {
            let repo_list: Vec<String> = g
                .repos
                .iter()
                .map(|r| {
                    reg.repos
                        .get(r)
                        .map(|e| format!("- `{}` — {}", r, e.path.display()))
                        .unwrap_or_else(|| format!("- `{}`", r))
                })
                .collect();
            Some(format!(
                "{GROUP_HEADING}`{}`\n\nThis repo is part of the `{}` microservice group. Other repos in this group:\n{}\n\nUse `group_query` with group name `{}` to query across all repos.\nUse `group_sync` then `group_deps` to find cross-service HTTP dependencies.\n",
                group_name, group_name, repo_list.join("\n"), group_name
            ))
        } else {
            println!(
                "  Warning: group '{}' not found in registry. Skipping group context.",
                group_name
            );
            None
        }
    } else {
        None
    };

    write_agent_instructions(root, group_context.as_deref())?;

    Ok(())
}

/// Read a single line from stdin, trimming whitespace.
fn read_line_stdin() -> String {
    let mut buf = String::new();
    let _ = std::io::stdin().read_line(&mut buf);
    buf.trim().to_string()
}

/// Walk the project directory and count files by language.
fn detect_languages(root: &Path) -> Vec<(String, usize)> {
    let ext_map: HashMap<&str, &str> = [
        ("rs", "Rust"),
        ("py", "Python"),
        ("js", "JavaScript"),
        ("ts", "TypeScript"),
        ("tsx", "TSX"),
        ("jsx", "JSX"),
        ("java", "Java"),
        ("kt", "Kotlin"),
        ("go", "Go"),
        ("rb", "Ruby"),
        ("c", "C"),
        ("cpp", "C++"),
        ("h", "C/C++ Header"),
        ("cs", "C#"),
        ("swift", "Swift"),
        ("scala", "Scala"),
        ("php", "PHP"),
        ("lua", "Lua"),
        ("zig", "Zig"),
        ("dart", "Dart"),
        ("ex", "Elixir"),
        ("exs", "Elixir"),
        ("hs", "Haskell"),
        ("pl", "Perl"),
        ("r", "R"),
        ("sql", "SQL"),
        ("proto", "Protocol Buffers"),
        ("graphql", "GraphQL"),
        ("gql", "GraphQL"),
        ("yaml", "YAML"),
        ("yml", "YAML"),
        ("toml", "TOML"),
        ("json", "JSON"),
        ("md", "Markdown"),
        ("sh", "Shell"),
        ("bash", "Shell"),
        ("zsh", "Shell"),
    ]
    .into_iter()
    .collect();

    let mut counts: HashMap<String, usize> = HashMap::new();
    walk_and_count(root, root, &ext_map, &mut counts, 0);

    let mut sorted: Vec<(String, usize)> = counts.into_iter().collect();
    sorted.sort_by_key(|b| std::cmp::Reverse(b.1));
    sorted
}

/// Recursively walk directories, counting files by extension.
/// Skips hidden dirs, node_modules, target, .git, etc.
fn walk_and_count(
    dir: &Path,
    _root: &Path,
    ext_map: &HashMap<&str, &str>,
    counts: &mut HashMap<String, usize>,
    depth: usize,
) {
    if depth > 20 {
        return;
    }

    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name_str = name.to_string_lossy();

        if name_str.starts_with('.') {
            continue;
        }

        if path.is_dir() {
            match name_str.as_ref() {
                "node_modules" | "target" | "dist" | "build" | "vendor" | "__pycache__"
                | "venv" | ".venv" | "out" | "obj" | "generated" | "third_party" | "CMakeFiles" => {
                    continue
                }
                _ => {}
            }
            walk_and_count(&path, _root, ext_map, counts, depth + 1);
        } else if path.is_file() {
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if let Some(&lang) = ext_map.get(ext) {
                    *counts.entry(lang.to_string()).or_insert(0) += 1;
                }
            }
        }
    }
}

/// Check for common directories/files and suggest .infigraphignore entries.
fn suggest_ignore_entries(root: &Path, languages: &[(String, usize)]) -> Vec<String> {
    let mut suggestions = Vec::new();

    let has_py = languages.iter().any(|(lang, _)| lang == "Python");

    if root.join("package.json").exists() {
        if root.join("node_modules").exists() {
            suggestions.push("node_modules/".to_string());
        }
        if root.join("dist").exists() {
            suggestions.push("dist/".to_string());
        }
    }

    if root.join("Cargo.toml").exists() && root.join("target").exists() {
        suggestions.push("target/".to_string());
    }

    if root.join("requirements.txt").exists() || root.join("pyproject.toml").exists() {
        if root.join("venv").exists() {
            suggestions.push("venv/".to_string());
        }
        if root.join(".venv").exists() {
            suggestions.push(".venv/".to_string());
        }
    }

    if (root.join("build.gradle").exists()
        || root.join("build.gradle.kts").exists()
        || root.join("pom.xml").exists())
        && root.join("build").exists()
    {
        suggestions.push("build/".to_string());
    }

    if has_py {
        suggestions.push("__pycache__/".to_string());
    }

    if (root.join("go.mod").exists() || root.join("Gemfile").exists())
        && root.join("vendor").exists()
    {
        suggestions.push("vendor/".to_string());
    }

    suggestions
}

pub(crate) fn infigraph_instructions() -> &'static str {
    // The same shared sources `infigraph install` deploys (#168), not a copy of
    // them: this text used to be a hand-maintained duplicate of agents.md and
    // drifted. None of these project-level targets can load skills, so the
    // tool-routing body is inlined, exactly as for the Cursor and Windsurf
    // install artifacts.
    concat!(
        include_str!("../resources/integrations/shared/agents.md"),
        "\n",
        include_str!("../resources/integrations/shared/tool-routing.md"),
    )
}

pub(crate) struct AgentInstructionTarget {
    pub path: &'static str,
    pub wrapper: fn(&str) -> String,
    pub label: &'static str,
}

pub(crate) fn wrap_plain(content: &str) -> String {
    content.to_string()
}

pub(crate) fn wrap_cursor_mdc(content: &str) -> String {
    format!(
        "---\ndescription: Infigraph code intelligence — use Infigraph MCP tools for all code navigation\nglobs: \nalwaysApply: true\n---\n\n{content}"
    )
}

pub(crate) fn wrap_kiro_rule(content: &str) -> String {
    format!("---\nname: infigraph\ndescription: Use Infigraph MCP tools for code navigation\ntype: always\n---\n\n{content}")
}

pub(crate) const AGENT_INSTRUCTION_TARGETS: &[AgentInstructionTarget] = &[
    AgentInstructionTarget {
        path: ".cursor/rules/infigraph.mdc",
        wrapper: wrap_cursor_mdc,
        label: "Cursor",
    },
    AgentInstructionTarget {
        path: ".github/copilot-instructions.md",
        wrapper: wrap_plain,
        label: "GitHub Copilot",
    },
    AgentInstructionTarget {
        path: ".windsurf/rules/infigraph.md",
        wrapper: wrap_plain,
        label: "Windsurf",
    },
    AgentInstructionTarget {
        path: ".kiro/rules/infigraph.md",
        wrapper: wrap_kiro_rule,
        label: "Kiro",
    },
    AgentInstructionTarget {
        path: "AGENTS.md",
        wrapper: wrap_plain,
        label: "Codex/OpenAI",
    },
    AgentInstructionTarget {
        path: "GEMINI.md",
        wrapper: wrap_plain,
        label: "Gemini CLI",
    },
];

/// Delimits the block `init` writes into each [`AGENT_INSTRUCTION_TARGETS`]
/// file; everything outside it is the project's own.
const INSTRUCTIONS_MARKER: &str = "<!-- infigraph-instructions -->";

/// Opens the section `init --group` appends to the instructions. A refresh
/// finds it by this heading and carries it over, since it has no group name.
const GROUP_HEADING: &str = "\n## This Repo's Group: ";

/// `existing` with its instructions block replaced by `block`, or with
/// `block` appended when it has none.
fn splice_block(existing: &str, block: &str) -> String {
    let marker = INSTRUCTIONS_MARKER;
    if let Some(start) = existing.find(marker) {
        let after_first = &existing[start + marker.len()..];
        let end = after_first
            .find(marker)
            .map(|p| start + marker.len() + p + marker.len())
            .unwrap_or(existing.len());
        format!("{}{}{}", &existing[..start], block, &existing[end..])
    } else if existing.is_empty() {
        block.to_string()
    } else {
        format!("{existing}\n\n{block}")
    }
}

/// `target`'s file content with the current instructions (plus
/// `group_context`, if any) spliced into `existing`.
fn render(target: &AgentInstructionTarget, existing: &str, group_context: Option<&str>) -> String {
    let base = infigraph_instructions();
    let instructions = match group_context {
        Some(ctx) => format!("{base}\n{ctx}"),
        None => base.to_string(),
    };
    let wrapped = (target.wrapper)(&instructions);
    let block = format!("{INSTRUCTIONS_MARKER}\n{wrapped}\n{INSTRUCTIONS_MARKER}");
    splice_block(existing, &block)
}

pub(crate) fn write_agent_instructions(
    root: &std::path::Path,
    group_context: Option<&str>,
) -> Result<()> {
    let mut written = Vec::new();

    for target in AGENT_INSTRUCTION_TARGETS {
        let file_path = root.join(target.path);

        if let Some(parent) = file_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let existing = std::fs::read_to_string(&file_path).unwrap_or_default();
        std::fs::write(&file_path, render(target, &existing, group_context))?;
        written.push(target.label);
    }

    if !written.is_empty() {
        println!("  Wrote agent instructions for: {}", written.join(", "));
    }

    Ok(())
}

/// Bring every instructions block `init` wrote up to date with this build.
///
/// Only `init` writes these files, so without this they kept whatever text
/// the build that ran `init` had, indefinitely (#207). A refresh touches only
/// a file that already holds a block -- it never creates a target the
/// project never had -- keeps any group section `init --group` added, and
/// writes nothing when the block is already current. Like the project
/// CLAUDE.md block, it applies only to a project store.
pub(crate) fn refresh_agent_instructions(root: &Path) -> Result<()> {
    if !infigraph_core::project::is_project_store(root) {
        return Ok(());
    }
    let mut refreshed = Vec::new();
    for target in AGENT_INSTRUCTION_TARGETS {
        let file_path = root.join(target.path);
        let Ok(existing) = std::fs::read_to_string(&file_path) else {
            continue;
        };
        let Some(start) = existing.find(INSTRUCTIONS_MARKER) else {
            continue;
        };
        let inner = &existing[start + INSTRUCTIONS_MARKER.len()..];
        let inner = inner
            .find(INSTRUCTIONS_MARKER)
            .map_or(inner, |end| &inner[..end]);
        let group_context = inner
            .find(GROUP_HEADING)
            .map(|at| inner[at..].strip_suffix('\n').unwrap_or(&inner[at..]));
        let updated = render(target, &existing, group_context);
        if updated != existing {
            std::fs::write(&file_path, updated)?;
            refreshed.push(target.label);
        }
    }
    if !refreshed.is_empty() {
        println!(
            "  Refreshed agent instructions for: {}",
            refreshed.join(", ")
        );
    }
    Ok(())
}

/// Refresh every infigraph-managed instructions block in `root`: the project
/// `.claude/CLAUDE.md` block and the blocks `init` wrote. Never fatal -- a
/// failure here is reported and indexing or watching carries on.
pub(crate) fn refresh_project_instructions(root: &Path) {
    if let Err(e) = infigraph_core::claude_md::ensure_project_claude_md(root) {
        eprintln!("warning: failed to update project CLAUDE.md: {e:#}");
    }
    if let Err(e) = refresh_agent_instructions(root) {
        eprintln!("warning: failed to refresh agent instructions: {e:#}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project() -> tempfile::TempDir {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join(".infigraph")).unwrap();
        std::fs::write(tmp.path().join(".infigraph").join("graph"), b"").unwrap();
        tmp
    }

    #[test]
    fn refresh_rewrites_a_stale_block_and_keeps_the_rest() {
        let root = project();
        let group = format!("{GROUP_HEADING}`g`\n\nOther repos.\n");
        std::fs::write(
            root.path().join("AGENTS.md"),
            format!(
                "# Mine\n\n{INSTRUCTIONS_MARKER}\nstale text{group}\n{INSTRUCTIONS_MARKER}\n\n## After\n"
            ),
        )
        .unwrap();

        refresh_agent_instructions(root.path()).unwrap();

        let text = std::fs::read_to_string(root.path().join("AGENTS.md")).unwrap();
        assert!(text.starts_with("# Mine\n"));
        assert!(text.ends_with("## After\n"));
        assert!(!text.contains("stale text"));
        assert!(text.contains(infigraph_instructions()));
        assert!(
            text.contains(&group),
            "the group section init wrote survives"
        );
        assert_eq!(text.matches(INSTRUCTIONS_MARKER).count(), 2);
    }

    #[test]
    fn refresh_never_creates_a_target() {
        let root = project();
        refresh_agent_instructions(root.path()).unwrap();
        for target in AGENT_INSTRUCTION_TARGETS {
            assert!(!root.path().join(target.path).exists(), "{}", target.path);
        }
    }

    #[test]
    fn refresh_leaves_a_non_project_alone() {
        let tmp = tempfile::tempdir().unwrap();
        let stale = format!("{INSTRUCTIONS_MARKER}\nstale\n{INSTRUCTIONS_MARKER}\n");
        std::fs::write(tmp.path().join("AGENTS.md"), &stale).unwrap();
        refresh_agent_instructions(tmp.path()).unwrap();
        assert_eq!(
            std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap(),
            stale
        );
    }

    #[test]
    fn an_unchanged_block_is_not_rewritten() {
        let root = project();
        write_agent_instructions(root.path(), None).unwrap();
        let path = root.path().join("AGENTS.md");
        let before = std::fs::metadata(&path).unwrap().modified().unwrap();
        std::thread::sleep(std::time::Duration::from_millis(20));
        refresh_agent_instructions(root.path()).unwrap();
        assert_eq!(
            std::fs::metadata(&path).unwrap().modified().unwrap(),
            before
        );
    }
}
